//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MantisBase2.Queries {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProjetoQueries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProjetoQueries() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MantisBase2.Queries.ProjetoQueries", typeof(ProjetoQueries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a DELETE FROM mantis_category_table where name=&apos;$categoria&apos;.
        /// </summary>
        internal static string DeleteCategoria {
            get {
                return ResourceManager.GetString("DeleteCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a DELETE FROM mantis_project_table where name=&apos;$nomeProjeto&apos;.
        /// </summary>
        internal static string DeleteProjeto {
            get {
                return ResourceManager.GetString("DeleteProjeto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT description FROM mantis_project_table WHERE NAME=&apos;$nomeProjeto&apos;.
        /// </summary>
        internal static string RetornaDescricao {
            get {
                return ResourceManager.GetString("RetornaDescricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT enabled FROM mantis_project_table WHERE NAME=&apos;$nomeProjeto&apos;.
        /// </summary>
        internal static string RetornaHabilitado {
            get {
                return ResourceManager.GetString("RetornaHabilitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT inherit_global FROM mantis_project_table WHERE NAME=&apos;$nomeProjeto&apos;.
        /// </summary>
        internal static string RetornaHerdarCategoriasGlobais {
            get {
                return ResourceManager.GetString("RetornaHerdarCategoriasGlobais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT count(*) FROM mantis_project_table WHERE NAME=&apos;$nomeProjeto&apos; AND STATUS=&apos;$status&apos; AND inherit_global=&apos;$headerCategoria&apos; AND view_state=&apos;$visibilidade&apos; AND description=&apos;$descricao&apos;.
        /// </summary>
        internal static string RetornaProjetoCadastrado {
            get {
                return ResourceManager.GetString("RetornaProjetoCadastrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT count(*) FROM mantis_project_table WHERE NAME=&apos;$nomeProjeto&apos;.
        /// </summary>
        internal static string RetornaQdteProjetoCadastrado {
            get {
                return ResourceManager.GetString("RetornaQdteProjetoCadastrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT count(*) FROM mantis_category_table where name=&apos;$categoria&apos;.
        /// </summary>
        internal static string RetornaQtdeCategoria {
            get {
                return ResourceManager.GetString("RetornaQtdeCategoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT count(*) FROM mantis_category_table where name=&apos;$categoria&apos; and user_id=&apos;$user&apos;.
        /// </summary>
        internal static string RetornaQtdeCategoriaAtribuido {
            get {
                return ResourceManager.GetString("RetornaQtdeCategoriaAtribuido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT status FROM mantis_project_table WHERE NAME=&apos;$nomeProjeto&apos;.
        /// </summary>
        internal static string RetornaStatusProjeto {
            get {
                return ResourceManager.GetString("RetornaStatusProjeto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT view_state FROM mantis_project_table WHERE NAME=&apos;$nomeProjeto&apos;.
        /// </summary>
        internal static string RetornaVisibilidade {
            get {
                return ResourceManager.GetString("RetornaVisibilidade", resourceCulture);
            }
        }
    }
}
