//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MantisBase2.Queries {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UsuariosQueries {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UsuariosQueries() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MantisBase2.Queries.UsuariosQueries", typeof(UsuariosQueries).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Delete from mantis_user_table where username = &apos;$username&apos;;.
        /// </summary>
        internal static string DeletaUsuario {
            get {
                return ResourceManager.GetString("DeletaUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT COUNT(*) FROM mantis_user_table where username = &apos;$username&apos;;.
        /// </summary>
        internal static string RetornaCountUsuarios {
            get {
                return ResourceManager.GetString("RetornaCountUsuarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT email FROM mantis_user_table where username = &apos;$username&apos;;.
        /// </summary>
        internal static string RetornaEmailUsuario {
            get {
                return ResourceManager.GetString("RetornaEmailUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT enabled FROM mantis_user_table where username = &apos;$username&apos;;.
        /// </summary>
        internal static string RetornaHabilitadoUsuario {
            get {
                return ResourceManager.GetString("RetornaHabilitadoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT access_level FROM mantis_user_table where username = &apos;$username&apos;;.
        /// </summary>
        internal static string RetornaNivelAcesso {
            get {
                return ResourceManager.GetString("RetornaNivelAcesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT username FROM mantis_user_table where username = &apos;$username&apos;;.
        /// </summary>
        internal static string RetornaNomeUsuario {
            get {
                return ResourceManager.GetString("RetornaNomeUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT realname FROM mantis_user_table where username = &apos;$username&apos;;.
        /// </summary>
        internal static string RetornaNomeVerdadeiroUsuarioCadastrado {
            get {
                return ResourceManager.GetString("RetornaNomeVerdadeiroUsuarioCadastrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT protected FROM mantis_user_table where username = &apos;$username&apos;;.
        /// </summary>
        internal static string RetornaProtegidoUsuario {
            get {
                return ResourceManager.GetString("RetornaProtegidoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT password FROM mantis_user_table where username = &apos;$username&apos;;.
        /// </summary>
        internal static string RetornaSenha {
            get {
                return ResourceManager.GetString("RetornaSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SELECT COUNT(*) FROM mantis_user_table where username = &apos;$username&apos; and realname = &apos;$nameTrue&apos; and email=&apos;$email&apos; and access_level = &apos;$acesso&apos; and enabled = &apos;$habilitado&apos; and protected=&apos;$protegido&apos;;.
        /// </summary>
        internal static string RetornaUsuarioCadastrado {
            get {
                return ResourceManager.GetString("RetornaUsuarioCadastrado", resourceCulture);
            }
        }
    }
}
